<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="5" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-03T23:43:07 PDT" name="Default suite" finished-at="2024-08-03T23:44:11 PDT" duration-ms="63135">
    <groups>
    </groups>
    <test started-at="2024-08-03T23:43:07 PDT" name="Default test" finished-at="2024-08-03T23:44:11 PDT" duration-ms="63135">
      <class name="testPackage.TestClass">
        <test-method is-config="true" signature="logger()[pri:0, instance:testPackage.TestClass@1573f9fc]" started-at="2024-08-03T23:43:07 PDT" name="logger" finished-at="2024-08-03T23:43:07 PDT" duration-ms="551" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logger -->
        <test-method signature="TestCase1()[pri:1, instance:testPackage.TestClass@1573f9fc]" started-at="2024-08-03T23:43:09 PDT" name="TestCase1" finished-at="2024-08-03T23:43:30 PDT" duration-ms="21330" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase1 -->
        <test-method signature="TestCase2()[pri:2, instance:testPackage.TestClass@1573f9fc]" started-at="2024-08-03T23:43:30 PDT" name="TestCase2" finished-at="2024-08-03T23:43:35 PDT" duration-ms="5131" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase2 -->
        <test-method signature="TestCase3()[pri:3, instance:testPackage.TestClass@1573f9fc]" started-at="2024-08-03T23:43:35 PDT" name="TestCase3" finished-at="2024-08-03T23:43:43 PDT" duration-ms="7606" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase3 -->
        <test-method signature="TestCase4()[pri:4, instance:testPackage.TestClass@1573f9fc]" started-at="2024-08-03T23:43:43 PDT" name="TestCase4" finished-at="2024-08-03T23:43:50 PDT" duration-ms="7647" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase4 -->
        <test-method signature="TestCase5()[pri:5, instance:testPackage.TestClass@1573f9fc]" started-at="2024-08-03T23:43:51 PDT" name="TestCase5" finished-at="2024-08-03T23:44:07 PDT" duration-ms="16809" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase5 -->
        <test-method signature="TestCase6()[pri:6, instance:testPackage.TestClass@1573f9fc]" started-at="2024-08-03T23:44:07 PDT" name="TestCase6" finished-at="2024-08-03T23:44:11 PDT" duration-ms="3295" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [822] but found [823]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [822] but found [823]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testPackage.TestClass.TestCase6(TestClass.java:111)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase6 -->
        <test-method is-config="true" signature="teardownMethod()[pri:0, instance:testPackage.TestClass@1573f9fc]" started-at="2024-08-03T23:44:12 PDT" name="teardownMethod" finished-at="2024-08-03T23:44:13 PDT" duration-ms="876" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardownMethod -->
      </class> <!-- testPackage.TestClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
